Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -57,21 +57,19 @@ jobs:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
 
-      - name: Deploy to remote server
+      - name: Deploy
         run: |
-          ssh -o StrictHostKeyChecking=no -p 58529 \
-          ${{ secrets.USER }}@${{ secrets.HOST }} \
-          "podman stop myapp || true && podman rm myapp || true"
-    
-          docker save myapp:final | ssh -p 58529 \
-          ${{ secrets.USER }}@${{ secrets.HOST }} \
-          "podman load && podman tag myapp:final myapp:final"
+          ssh -o ConnectTimeout=15 -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} exit || {
+          echo "Cannot connect to server";
+          exit 1;}
 
-          ssh -o StrictHostKeyChecking=no \
-          -p ${{ secrets.PORT }} \
-          ${{ secrets.USER }}@${{ secrets.HOST }} \
-          "podman stop myapp || true && \
-          podman rm myapp || true && \
-          podman run -d --name myapp \
-          --network=host \
-          myapp:final"
+          docker save myapp:final | ssh -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} "
+          podman load || exit 1
+          podman tag myapp:final myapp:final || exit 1
+          "
+
+          ssh -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} "
+          podman stop myapp || true
+          podman rm myapp || true
+          podman run -d --name myapp --network=host myapp:final
+          "
